# Github Pages preferences (do not change)
github:           [metadata]
highlighter:      rouge

# Enable the following Github Pages optional Plugins
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-sitemap

# Repository configuration
repository:       
version:          2.4.1

# Jekyll site configuration
title:            test
title_separator:  "&middot;"
tagline:          Open Source Technologist &amp;&nbsp;Senior&nbsp;Web&nbsp;Developer
description: >-   # Used in homepage metatag and RSS feed description.
                  The personal blog of James Wilson; senior web developer
                  at Bluespark and avid Open Source enthusiast.
url:              https://bgigi/jekyllblog.io
baseurl:          # the subpath of your site, e.g. "/blog"
permalink:        /:year-:month-:day-:title
paginate:         3

# og:image metatag default (override this per post/page in post's front matter)

# Jekyll Feed plugin options
feed:
  path: atom.xml  # override the default /feed.xml

# Main navigation links.
# See _includes/navigation.html for usage.
navigation:
  - title: Blog
    url: /
  - title: Archives
    url: /archives
  - title: About
    url: /about
  - title: Search
    url: /search

# Defaults
defaults:
  # all posts
  -
    scope:
      path: ""
      type: posts
    values:
      type: post
      schema_type: BlogPosting
      og_type: article
  # all pages
  -
    scope:
      path: ""
      type: pages
    values:
      type: page
      schema_type: CreativeWork
      og_type: article
  # homepage
  -
    scope:
      path: "index.html"
    values:
      type: homepage
      schema_type: Blog # or WebSite  (see schema.org)
      og_type: website
  # authorpage provides special Structured Data about the author.
  # Modify the "scope.path" as necessary to match whatever you use for the
  # site's author biography page.
  -
    scope:
      path: "_pages/about.md"
    values:
      type: authorpage
      schema_type: AboutPage
      og_type: article
  # search results page
  -
    scope:
      path: "_pages/search.md"
    values:
      type: searchresultspage
      schema_type: SearchResultsPage
  # archive pages (by year, categories, tags)
  -
    scope:
      type: archive
    values:
      schema_type: CollectionPage

# Process pages in the following additional custom subfolders.
# Note these pages must use the 'permalink' parameter in yaml front matter
# in order for Jekyll to place them correctly into the site's url structure.
include:
  - _pages
  - _redirect
  - _favicon

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
